Docker Compose 
--------------------

A templated docker container deployment.
Orchestrates a bunch of docker commands in an easy to read way.

It transforms or translates a templated yaml file into docker commands.
Allows us to easily version control deployments.

Example:

docker-compose.yml
------------------------
version: '3.1'

services:
    tomcat1:
        image: tomcat:latest
        ports:
            - 1002:80
            - 1003:80
            - 1023:80
    tomcat2:
        image: tomcat:latest
        ports:
            - 1004:80
            - 1005:8080
            
        environment:
            TEST_ENV_VAR: test1234
        
        


to run a docker compose file
-----------------------------

docker-compose up                   (It searches for docker-compose.yml)
docker-compose -f filename.yml
docker-compose -d -f filename.yml   


Example-2
------------------
docker-compose.yml
-------------------

version: '3.1'

services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            
    adminer:
        image: adminer:latest
        restart: always
        ports:
            - 8080:80
            
            
            
Run
------

docker-compose up -d
